// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"CN-EU-FSIMS/internal/app/models/warehouse"
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newPackWarehouse(db *gorm.DB, opts ...gen.DOOption) packWarehouse {
	_packWarehouse := packWarehouse{}

	_packWarehouse.packWarehouseDo.UseDB(db, opts...)
	_packWarehouse.packWarehouseDo.UseModel(&warehouse.PackWarehouse{})

	tableName := _packWarehouse.packWarehouseDo.TableName()
	_packWarehouse.ALL = field.NewAsterisk(tableName)
	_packWarehouse.ID = field.NewUint(tableName, "id")
	_packWarehouse.CreatedAt = field.NewTime(tableName, "created_at")
	_packWarehouse.UpdatedAt = field.NewTime(tableName, "updated_at")
	_packWarehouse.DeletedAt = field.NewField(tableName, "deleted_at")
	_packWarehouse.ProductNumber = field.NewString(tableName, "product_number")
	_packWarehouse.PID = field.NewString(tableName, "p_id")
	_packWarehouse.Type = field.NewString(tableName, "type")
	_packWarehouse.State = field.NewUint(tableName, "state")
	_packWarehouse.InOperator = field.NewString(tableName, "in_operator")
	_packWarehouse.InTimestamp = field.NewTime(tableName, "in_timestamp")
	_packWarehouse.OutTimestamp = field.NewTime(tableName, "out_timestamp")
	_packWarehouse.PacNumber = field.NewString(tableName, "pac_number")

	_packWarehouse.fillFieldMap()

	return _packWarehouse
}

type packWarehouse struct {
	packWarehouseDo packWarehouseDo

	ALL           field.Asterisk
	ID            field.Uint
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	ProductNumber field.String
	PID           field.String
	Type          field.String
	State         field.Uint
	InOperator    field.String
	InTimestamp   field.Time
	OutTimestamp  field.Time
	PacNumber     field.String

	fieldMap map[string]field.Expr
}

func (p packWarehouse) Table(newTableName string) *packWarehouse {
	p.packWarehouseDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p packWarehouse) As(alias string) *packWarehouse {
	p.packWarehouseDo.DO = *(p.packWarehouseDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *packWarehouse) updateTableName(table string) *packWarehouse {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.ProductNumber = field.NewString(table, "product_number")
	p.PID = field.NewString(table, "p_id")
	p.Type = field.NewString(table, "type")
	p.State = field.NewUint(table, "state")
	p.InOperator = field.NewString(table, "in_operator")
	p.InTimestamp = field.NewTime(table, "in_timestamp")
	p.OutTimestamp = field.NewTime(table, "out_timestamp")
	p.PacNumber = field.NewString(table, "pac_number")

	p.fillFieldMap()

	return p
}

func (p *packWarehouse) WithContext(ctx context.Context) IPackWarehouseDo {
	return p.packWarehouseDo.WithContext(ctx)
}

func (p packWarehouse) TableName() string { return p.packWarehouseDo.TableName() }

func (p packWarehouse) Alias() string { return p.packWarehouseDo.Alias() }

func (p packWarehouse) Columns(cols ...field.Expr) gen.Columns {
	return p.packWarehouseDo.Columns(cols...)
}

func (p *packWarehouse) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *packWarehouse) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["product_number"] = p.ProductNumber
	p.fieldMap["p_id"] = p.PID
	p.fieldMap["type"] = p.Type
	p.fieldMap["state"] = p.State
	p.fieldMap["in_operator"] = p.InOperator
	p.fieldMap["in_timestamp"] = p.InTimestamp
	p.fieldMap["out_timestamp"] = p.OutTimestamp
	p.fieldMap["pac_number"] = p.PacNumber
}

func (p packWarehouse) clone(db *gorm.DB) packWarehouse {
	p.packWarehouseDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p packWarehouse) replaceDB(db *gorm.DB) packWarehouse {
	p.packWarehouseDo.ReplaceDB(db)
	return p
}

type packWarehouseDo struct{ gen.DO }

type IPackWarehouseDo interface {
	gen.SubQuery
	Debug() IPackWarehouseDo
	WithContext(ctx context.Context) IPackWarehouseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPackWarehouseDo
	WriteDB() IPackWarehouseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPackWarehouseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPackWarehouseDo
	Not(conds ...gen.Condition) IPackWarehouseDo
	Or(conds ...gen.Condition) IPackWarehouseDo
	Select(conds ...field.Expr) IPackWarehouseDo
	Where(conds ...gen.Condition) IPackWarehouseDo
	Order(conds ...field.Expr) IPackWarehouseDo
	Distinct(cols ...field.Expr) IPackWarehouseDo
	Omit(cols ...field.Expr) IPackWarehouseDo
	Join(table schema.Tabler, on ...field.Expr) IPackWarehouseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPackWarehouseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPackWarehouseDo
	Group(cols ...field.Expr) IPackWarehouseDo
	Having(conds ...gen.Condition) IPackWarehouseDo
	Limit(limit int) IPackWarehouseDo
	Offset(offset int) IPackWarehouseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPackWarehouseDo
	Unscoped() IPackWarehouseDo
	Create(values ...*warehouse.PackWarehouse) error
	CreateInBatches(values []*warehouse.PackWarehouse, batchSize int) error
	Save(values ...*warehouse.PackWarehouse) error
	First() (*warehouse.PackWarehouse, error)
	Take() (*warehouse.PackWarehouse, error)
	Last() (*warehouse.PackWarehouse, error)
	Find() ([]*warehouse.PackWarehouse, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*warehouse.PackWarehouse, err error)
	FindInBatches(result *[]*warehouse.PackWarehouse, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*warehouse.PackWarehouse) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPackWarehouseDo
	Assign(attrs ...field.AssignExpr) IPackWarehouseDo
	Joins(fields ...field.RelationField) IPackWarehouseDo
	Preload(fields ...field.RelationField) IPackWarehouseDo
	FirstOrInit() (*warehouse.PackWarehouse, error)
	FirstOrCreate() (*warehouse.PackWarehouse, error)
	FindByPage(offset int, limit int) (result []*warehouse.PackWarehouse, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPackWarehouseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p packWarehouseDo) Debug() IPackWarehouseDo {
	return p.withDO(p.DO.Debug())
}

func (p packWarehouseDo) WithContext(ctx context.Context) IPackWarehouseDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p packWarehouseDo) ReadDB() IPackWarehouseDo {
	return p.Clauses(dbresolver.Read)
}

func (p packWarehouseDo) WriteDB() IPackWarehouseDo {
	return p.Clauses(dbresolver.Write)
}

func (p packWarehouseDo) Session(config *gorm.Session) IPackWarehouseDo {
	return p.withDO(p.DO.Session(config))
}

func (p packWarehouseDo) Clauses(conds ...clause.Expression) IPackWarehouseDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p packWarehouseDo) Returning(value interface{}, columns ...string) IPackWarehouseDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p packWarehouseDo) Not(conds ...gen.Condition) IPackWarehouseDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p packWarehouseDo) Or(conds ...gen.Condition) IPackWarehouseDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p packWarehouseDo) Select(conds ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p packWarehouseDo) Where(conds ...gen.Condition) IPackWarehouseDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p packWarehouseDo) Order(conds ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p packWarehouseDo) Distinct(cols ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p packWarehouseDo) Omit(cols ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p packWarehouseDo) Join(table schema.Tabler, on ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p packWarehouseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p packWarehouseDo) RightJoin(table schema.Tabler, on ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p packWarehouseDo) Group(cols ...field.Expr) IPackWarehouseDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p packWarehouseDo) Having(conds ...gen.Condition) IPackWarehouseDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p packWarehouseDo) Limit(limit int) IPackWarehouseDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p packWarehouseDo) Offset(offset int) IPackWarehouseDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p packWarehouseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPackWarehouseDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p packWarehouseDo) Unscoped() IPackWarehouseDo {
	return p.withDO(p.DO.Unscoped())
}

func (p packWarehouseDo) Create(values ...*warehouse.PackWarehouse) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p packWarehouseDo) CreateInBatches(values []*warehouse.PackWarehouse, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p packWarehouseDo) Save(values ...*warehouse.PackWarehouse) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p packWarehouseDo) First() (*warehouse.PackWarehouse, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*warehouse.PackWarehouse), nil
	}
}

func (p packWarehouseDo) Take() (*warehouse.PackWarehouse, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*warehouse.PackWarehouse), nil
	}
}

func (p packWarehouseDo) Last() (*warehouse.PackWarehouse, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*warehouse.PackWarehouse), nil
	}
}

func (p packWarehouseDo) Find() ([]*warehouse.PackWarehouse, error) {
	result, err := p.DO.Find()
	return result.([]*warehouse.PackWarehouse), err
}

func (p packWarehouseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*warehouse.PackWarehouse, err error) {
	buf := make([]*warehouse.PackWarehouse, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p packWarehouseDo) FindInBatches(result *[]*warehouse.PackWarehouse, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p packWarehouseDo) Attrs(attrs ...field.AssignExpr) IPackWarehouseDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p packWarehouseDo) Assign(attrs ...field.AssignExpr) IPackWarehouseDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p packWarehouseDo) Joins(fields ...field.RelationField) IPackWarehouseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p packWarehouseDo) Preload(fields ...field.RelationField) IPackWarehouseDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p packWarehouseDo) FirstOrInit() (*warehouse.PackWarehouse, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*warehouse.PackWarehouse), nil
	}
}

func (p packWarehouseDo) FirstOrCreate() (*warehouse.PackWarehouse, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*warehouse.PackWarehouse), nil
	}
}

func (p packWarehouseDo) FindByPage(offset int, limit int) (result []*warehouse.PackWarehouse, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p packWarehouseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p packWarehouseDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p packWarehouseDo) Delete(models ...*warehouse.PackWarehouse) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *packWarehouseDo) withDO(do gen.Dao) *packWarehouseDo {
	p.DO = *do.(*gen.DO)
	return p
}
