// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                           = new(Query)
	LatencyResult               *latencyResult
	ScalabilityItem             *scalabilityItem
	ScalabilityLatencyResult    *scalabilityLatencyResult
	ScalabilityThroughputResult *scalabilityThroughputResult
	ThroughputResult            *throughputResult
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	LatencyResult = &Q.LatencyResult
	ScalabilityItem = &Q.ScalabilityItem
	ScalabilityLatencyResult = &Q.ScalabilityLatencyResult
	ScalabilityThroughputResult = &Q.ScalabilityThroughputResult
	ThroughputResult = &Q.ThroughputResult
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                          db,
		LatencyResult:               newLatencyResult(db, opts...),
		ScalabilityItem:             newScalabilityItem(db, opts...),
		ScalabilityLatencyResult:    newScalabilityLatencyResult(db, opts...),
		ScalabilityThroughputResult: newScalabilityThroughputResult(db, opts...),
		ThroughputResult:            newThroughputResult(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	LatencyResult               latencyResult
	ScalabilityItem             scalabilityItem
	ScalabilityLatencyResult    scalabilityLatencyResult
	ScalabilityThroughputResult scalabilityThroughputResult
	ThroughputResult            throughputResult
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                          db,
		LatencyResult:               q.LatencyResult.clone(db),
		ScalabilityItem:             q.ScalabilityItem.clone(db),
		ScalabilityLatencyResult:    q.ScalabilityLatencyResult.clone(db),
		ScalabilityThroughputResult: q.ScalabilityThroughputResult.clone(db),
		ThroughputResult:            q.ThroughputResult.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                          db,
		LatencyResult:               q.LatencyResult.replaceDB(db),
		ScalabilityItem:             q.ScalabilityItem.replaceDB(db),
		ScalabilityLatencyResult:    q.ScalabilityLatencyResult.replaceDB(db),
		ScalabilityThroughputResult: q.ScalabilityThroughputResult.replaceDB(db),
		ThroughputResult:            q.ThroughputResult.replaceDB(db),
	}
}

type queryCtx struct {
	LatencyResult               ILatencyResultDo
	ScalabilityItem             IScalabilityItemDo
	ScalabilityLatencyResult    IScalabilityLatencyResultDo
	ScalabilityThroughputResult IScalabilityThroughputResultDo
	ThroughputResult            IThroughputResultDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		LatencyResult:               q.LatencyResult.WithContext(ctx),
		ScalabilityItem:             q.ScalabilityItem.WithContext(ctx),
		ScalabilityLatencyResult:    q.ScalabilityLatencyResult.WithContext(ctx),
		ScalabilityThroughputResult: q.ScalabilityThroughputResult.WithContext(ctx),
		ThroughputResult:            q.ThroughputResult.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
