runmode: debug # 开发模式, debug, release, test

server:
  ip_addr: 127.0.0.1
  port: 8000

mysql:
  username: root
  password: 123456
  ip_addr: 127.0.0.1
  port: 3306
  database: fsims

jwt:
  # token 过期时间 单位：秒
  timeout: 3600

log:
  output_path: server/output/log/


casbin:
  model_path: D:\A-中欧\CN-EU-FSIMS\conf\casbin\fsims_rbac_model.conf
  role_policy_path : D:\A-中欧\CN-EU-FSIMS\conf\casbin\fsims_rbac_role_policy.csv
  user_role_path: D:\A-中欧\CN-EU-FSIMS\conf\casbin\fsims_rbac_user_role.csv


#admin:
#  sec_admin_username: secadmin
#  sys_admin_username: sysadmin
#  auditor_username: auditor
#


#jwt:
#  # token 密钥，生产环境时及的修改
#  secret: sfm
#  # token 过期时间 单位：秒
#  timeout: 3600
#dsfs:
#  #dsfs1: 8.210.51.255:5001
#  dsfs1: 192.168.1.106:5001
#  #dsfs1: 192.168.1.119:5001
#test:
##  test1: 192.168.1.245:9092
##  test2: 192.168.1.245:9092
##  test3: 192.168.1.245:9092

