// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUploadImg = "upload_imgs"

// UploadImg mapped from table <upload_imgs>
type UploadImg struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Filename   string    `gorm:"column:filename;not null" json:"filename"`
	Result     string    `gorm:"column:result;not null" json:"result"`
	Source     string    `gorm:"column:source;not null" json:"source"`
	UploadTime time.Time `gorm:"column:upload_time;default:CURRENT_TIMESTAMP" json:"upload_time"`
}

// TableName UploadImg's table name
func (*UploadImg) TableName() string {
	return TableNameUploadImg
}
